/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: a60e117445f48f2dd26ba8b11b65c578)
interface __BaseEnv_Env {
	DB: D1Database;
	ENVIRONMENT: "local";
	CLOUD_ENABLED: "false";
	AUTH_ORIGIN: "http://127.0.0.1:8787";
	BETTER_AUTH_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "CLOUD_ENABLED" | "AUTH_ORIGIN" | "BETTER_AUTH_SECRET">> {}
}
