/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 7f834bcd2de770cca74430f3a45e3cc6)
interface __BaseEnv_Env {
	DB: D1Database;
	EMAIL: SendEmail;
	ENVIRONMENT: "local";
	CLOUD_ENABLED: "false";
	AUTH_ENABLED: "false";
	AUTH_ORIGIN: "http://127.0.0.1:8787";
	GOOGLE_CLIENT_ID: "";
	EMAIL_LOGIN_ENABLED: "false";
	EMAIL_FROM: "login@getziki.com";
	BETTER_AUTH_SECRET: string;
	GOOGLE_CLIENT_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "CLOUD_ENABLED" | "AUTH_ENABLED" | "AUTH_ORIGIN" | "GOOGLE_CLIENT_ID" | "EMAIL_LOGIN_ENABLED" | "EMAIL_FROM" | "BETTER_AUTH_SECRET" | "GOOGLE_CLIENT_SECRET">> {}
}
